import { Meal } from './constants';

export const meals: Meal[] = [
  {
    id: '1',
    date: '12/04/2024',
    name: 'X-Tudo',
    description: 'Xis completo da lancheria do bairro',
    hour: '20:00',
    on_diet: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '2',
    date: '12/04/2024',
    name: 'Sanduíche',
    description: 'Sanduíche de pão integral com atum e salada de alface e tomate',
    hour: '16:00',
    on_diet: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '3',
    date: '12/04/2024',
    name: 'Lasanha de frango com queijo',
    description: 'Lasanha de frango com queijo',
    hour: '12:30',
    on_diet: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '4',
    date: '12/04/2024',
    name: 'Torta de chocolate',
    description: 'Torta de chocolate',
    hour: '09:30',
    on_diet: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '5',
    date: '11/04/2024',
    name: 'X-Tudo',
    description: 'X-Tudo',
    hour: '20:00',
    on_diet: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '6',
    date: '11/04/2024',
    name: 'Whey Protein com Leite',
    description: 'Whey Protein com Leite',
    hour: '16:00',
    on_diet: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '7',
    date: '11/04/2024',
    name: 'Salada Cesar com Frango',
    description: 'Salada Cesar com Frango',
    hour: '12:30',
    on_diet: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '8',
    date: '11/04/2024',
    name: 'Vitamina de Banana com Abacate',
    description: 'Vitamina de Banana com Abacate',
    hour: '09:30',
    on_diet: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
